project:
  type: website
  output-dir: ./docs/

website:
  title: "Learning resources"
  navbar:
    left:
      - text: "Foundations of sport and exercise psychology"
        href: FoundationsOfSportExercisePsychology.html
      - text: "Foundations of motivation"
        href: FoundationsOfMotivation.html
      - text: "Foundations of the brain"
        href: FoundationsOfTheBrain.html
      - text: "Foundations of attention"
        href: FoundationsOfAttention.html
      - text: "Foundations of executive functions"
        href: FoundationsOfExecutiveFunctions.html
      - text: "Foundations of brain and fatigue"
        href: FoundationsOfBrainAndFatigue.html
      - text: "Foundations of scientific reading"
        href: FoundationsOfScientificReading.html
      - text: "Attentional Control Theory"
        href: AttentionalControlTheory.html
format: 
    revealjs:
        width: 1280     # slide width in pixels
        height: 720     # slide height in pixels
        margin: 0.01       # margin around slides (default is 0.1 = 10%)
        incremental: true
        center-title-slide: false
        center: false
        slide-number: true
        preview-links: false
        progress: true
        transition: fade
        theme: simple
        chalkboard: true
        scrollable: false
        touch: true
        controls: false
        vertical-sections: false
        audio-slideshow: true
        css: custom.css
