---
title: "Learning Resources"
format: html
---

### Psychophysiology

| Topic | RevealJS Slides | Mobile-Friendly View | PDF Document |
|--------------|-----------------|----------------------|--------------|
| Biosignals: concepts | [slides] | [scroll view] | [pdf] |
| Biosignals: processing basics | [slides] | [scroll view] | [pdf] |
| Oculomotor system and electrooculography | [slides](Psychophysiology_OculomotorEOG.html) | [scroll view](Psychophysiology_OculomotorEOG.html?view=scroll) | [pdf](Psychophysiology_OculomotorEOG.pdf) |
| Electrooculography acquisition workshop | [slides](Psychophysiology_EOGAcquisitionWorkshop.html) | [scroll view](Psychophysiology_EOGAcquisitionWorkshop.html?view=scroll) | [pdf](Psychophysiology_EOGAcquisitionWorkshop.pdf) |
| Electrooculography processing workshop | [slides](Psychophysiology_EOGProcessingWorkshop.html) | [scroll view](EOGProcessingWorkshop.html?view=scroll) | [pdf](EOGProcessingWorkshop.pdf) |
| Cortical system and electroencephalography | [slides] | [scroll view] | [pdf] |
| Electroencephalography acquisition workshop | [slides] | [scroll view] | [pdf] |
| Electroencephalography processing workshop | [slides](Psychophysiology_EEGProcessingWorkshop.html) | [scroll view](EEGProcessingWorkshop.html?view=scroll) | [pdf](EEGProcessingWorkshop.pdf) |
| Hot topics in sport & exercise: Quiet Eye | [slides](Psychophysiology_QuietEye.html) | [scroll view](Psychophysiology_QuietEye.html?view=scroll) | [pdf](Psychophysiology_QuietEye.pdf) |
| Hot topics in sport & exercise: Psychomotor efficiency | [slides] | [scroll view] | [pdf] |
 

<!--| Biosignals: sources and propagation | - | - | - |
| Biosignals: acquisition | - | - | - |
| Biosignals: processing theory | - | - | - |
| Biosignals: processing practice  | - | - | - |
| Oculomotor system | - | - | - |
| Electrooculography | - | - | - |
| Cortical system | - | - | - |
| Electroencephalography | - | - | - |
-->


see also: 

- "Principles of Psychophysiology" and "Psychophysiology Laboratory" by John Allen: [link](https://psychophyslab.arizona.edu/courses)
- "Teacher Training Material" by Society for Psychophysiological Research: [link](https://sprweb.org/teaching_material/)


### Cognitive neuroscience

| Topic | RevealJS Slides | Mobile-Friendly View | PDF Document |
|--------------|-----------------|----------------------|--------------|
| Foundations of the Brain | [slides](FoundationsOfTheBrain.html) | [scroll view](FoundationsOfTheBrain.html?view=scroll) | [pdf](FoundationsOfTheBrain.pdf) |
| Foundations of Attention | [slides](FoundationsOfAttention.html) | [scroll view](FoundationsOfAttention.html?view=scroll) | [pdf](FoundationsOfAttention.pdf) |
| Foundations of Executive Functions | [slides](FoundationsOfExecutiveFunctions.html) | [scroll view](FoundationsOfExecutiveFunctions.html?view=scroll) | [pdf](FoundationsOfExecutiveFunctions.pdf) |
| Attentional Control Theory | [slides](AttentionalControlTheory.html) | [scroll view](AttentionalControlTheory.html?view=scroll) | [pdf](AttentionalControlTheory.pdf) |

### Psychology

| Topic | RevealJS Slides | Mobile-Friendly View | PDF Document |
|--------------|-----------------|----------------------|--------------|
| Foundations of Sport and Exercise Psychology | [slides](FoundationsOfSportExercisePsychology.html) | [scroll view](FoundationsOfSportExercisePsychology.html?view=scroll) | [pdf](FoundationsOfSportExercisePsychology.pdf) |
| Foundations of Motivation | [slides](FoundationsOfMotivation.html) | [scroll view](FoundationsOfMotivation.html?view=scroll) | [pdf](FoundationsOfMotivation.pdf) |
| Foundations of self-control and fatigue | [slides](FoundationsOfSelfControlAndFatigue.html) | [scroll view](FoundationsOfSelfControlAndFatigue.html?view=scroll) | [pdf](FoundationsOfSelfControlAndFatigue.pdf) |
| Foundations of Scientific Reading | [slides](FoundationsOfScientificReading.html) | [scroll view](FoundationsOfScientificReading.html?view=scroll) | [pdf](FoundationsOfScientificReading.pdf) |
