## Workshop: Basic processing {.nostretch .center}

::::{.columns}
:::{.column width=80%}

Dr Germano Gallicchio <br>
<div style="font-size:0.8em">
Lecturer in Psychophysiology and Cognitive Neuroscience

School of Psychology and Sport Science, Bangor University, UK <br>

[profile](https://www.bangor.ac.uk/staff/spss/germano-gallicchio-530785/en) | [research](https://scholar.google.com/citations?user=i3h3GbMAAAAJ&hl=en) | [software](https://github.com/GermanoGallicchio) | [learning resources](https://germanogallicchio.github.io/learning/) | [book meeting](https://outlook.office.com/book/SHESStaffTutorialandDropInHours@bangoroffice365.onmicrosoft.com/?login_hint)
</div>

<br>

::: {.content-visible when-format="html"}
<div style="font-size:0.6em">
On a computer press F11 to de/activate full-screen view.

For smartphone and review: Bottom left menu -> Tools -> PDF Export Mode.

For pdf document: use "learning resources" link above.

Last modified: {{< meta date-modified >}}
</div>
:::

:::

:::{.column width=20%}
::: {.content-visible when-format="html"}
QR code to<br>these slides:
{{< qrcode https://germanogallicchio.github.io/learning/Psychophysiology_BasicProcessingWorkshop.html?view=scroll colorDark='#0011bb' >}}
:::

::: {.content-visible when-format="pdf"}
[To access the latest version of these slides or other learning material visit this link](https://germanogallicchio.github.io/learning/)
:::

<br>

::: {.content-visible when-format="html"}
<span class="pulse" style="font-weight: bold; color: rgba(255,40,0,0.6);">PIN</span>
<div contenteditable="true" style="
    min-height: 0;
    padding: 0;
    font-size: 2.5em;
    color: rgba(255,40,0,0.6)
">0000</div>
:::
:::
::::

<style>
.pulse {
  animation: pulse 2s ease-in-out infinite;
}

@keyframes pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.3; }
}
</style>

# Overview

This workshop provides hands-on experience with **coding concepts** necessary for basic biosignal processing.

[Students will go through computer code to carry out tasks of gradually increasing complexity.]{.fragment}

[These tasks are not directly related to psychophysiology, but they are designed to teach the coding concepts that are necessary for basic biosignal processing.]{.fragment}

[The sequence of tasks is designed to progress from no knowledge of coding to enough to be able to carry out basic biosignal processing in later sessions.]{.fragment}

[Once these fundamental coding concepts are covered, we will be able to apply them to psychophysiological data in later sessions.]{.fragment}

# Learning outcomes

By the end of this workshop, students will be able to:

- Navigate a MATLAB script and identify key sections (setup, operations, outputs)
- Work with basic data types and simple data structures in MATLAB.
- Create, load, and inspect simple datasets for practice analyses.
- Generate and interpret basic plots of time-series data.
- Describe how signals can be represented in time and frequency terms.
- Apply simple, exploratory filtering steps and compare outcomes.


# Requirements {.scrollable}

1. **MATLAB**
The computer code is written in MATLAB (https://en.wikipedia.org/wiki/MATLAB), a programming language often used for numerical computations in psychophysiology. To run MATLAB code you will need to use MATLAB software.

2. **Scripts**
Scripts from the "Learn Psychophysiology" repository:
[https://github.com/GermanoGallicchio/LearnPsychophysiology](https://github.com/GermanoGallicchio/LearnPsychophysiology)

:::aside
Make sure you have installed all the required software and downloaded the scripts before starting the workshop.
:::

# Workshop structure

The workshop is designed to be interactive, with students following along with the provided MATLAB scripts.

For this session, we will use these scripts:

pp01_*.m

[Let's switch to MATLAB and start working on the code.]{.fragment}
