project:
  type: website
  output-dir: ../docs/JXHC_1055

format: 
    revealjs:
        incremental: true
        center-title-slide: true
        center: false
        slide-number: true
        preview-links: false
        progress: true
        transition: fade
        theme: solarized