project:
  type: website
  output-dir: ../docs/JXHC_1055

website:
  title: "JXHC 1055"
  navbar:
    left:
      - text: "Session 1"
        href: 01.qmd
      - text: "Session 2"
        href: 02.qmd

format: 
    revealjs:
        width: 1280     # slide width in pixels
        height: 720     # slide height in pixels
        margin: 0.02       # margin around slides (default is 0.1 = 10%)
        incremental: true
        center-title-slide: false
        center: false
        slide-number: true
        preview-links: false
        progress: true
        transition: fade
        theme: simple
        chalkboard: true
        scrollable: true
        touch: false
        controls: true
        css: custom.css