project:
  type: website
  output-dir: ../docs/JXHC_1055

website:
  title: "JXHC 1055"
  navbar:
    left:
      - text: "Session 1"
        href: 01.qmd
      - text: "Session 2"
        href: 02.qmd

format: 
    revealjs:
        incremental: true
        center-title-slide: true
        center: false
        slide-number: true
        preview-links: false
        progress: true
        transition: fade
        theme: simple
        chalkboard: true
        css: custom.css